import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, CheckCircle2, FileBarChart, Landmark, ShieldCheck } from "lucide-react";
import heroImage from "@/assets/banknilami-hero.jpg";
import { Button } from "@/components/ui/button";
import { AuctionCard, ComplianceList, ContactForm, CTASection, DashboardMock, JourneyTimeline, PartnerGrid, ProcessValueFlow, ReasonsGrid, ServiceGrid, Stats } from "@/components/content";
import { SectionHeading } from "@/components/site";
import { auctions, offices } from "@/lib/site-data";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:"Bank Property Auction Services | bankNilami.com"},{name:"description",content:"End-to-end bank property auction management for Banks, NBFCs, HFCs and Co-operative Banks across India."},{property:"og:title",content:"Bank Property Auction Services | bankNilami.com"},{property:"og:description",content:"From stress to realisation through one managed auction ecosystem."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"https://banknilami.com/"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:"bankNilami.com",legalName:"Citiline Technologies Private Limited",url:"https://banknilami.com",email:"info.banknilami@gmail.com",telephone:"+91-8094000405",areaServed:"India"})}]}),
  component: Home,
});

function Home(){return <>
  <section className="relative min-h-[760px] overflow-hidden bg-navy text-navy-foreground"><img src={heroImage} alt="Institutional commercial property inspection" width={1536} height={1024} fetchPriority="high" className="absolute inset-0 size-full object-cover object-center"/><div className="hero-shade absolute inset-0"/><div className="section-shell relative flex min-h-[760px] flex-col justify-center py-20"><div className="animate-rise max-w-3xl"><p className="mb-6 text-xs font-bold uppercase tracking-[0.24em] text-gold">Bank Property Auction Services</p><h1 className="display-serif text-5xl font-semibold leading-[1.02] sm:text-6xl lg:text-8xl">From Stress to Realisation.<br/><em className="font-medium text-gold">One Managed Ecosystem.</em></h1><p className="mt-7 max-w-2xl text-base leading-8 text-navy-foreground/75 lg:text-lg">bankNilami.com manages secured property auctions on behalf of Banks, NBFCs, HFCs and Co-operative Banks — from valuation-readiness through sale confirmation and final account settlement.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild variant="premium" size="lg"><Link to="/contact">Partner With Us <ArrowRight/></Link></Button><Button asChild variant="light" size="lg"><Link to="/auctions">Explore Auction Properties</Link></Button></div></div><div className="animate-rise-delay mt-16 max-w-5xl"><Stats dark/></div></div></section>
  <section className="border-b border-border bg-background"><div className="section-shell flex flex-col items-center justify-between gap-6 py-7 lg:flex-row"><p className="text-xs font-bold uppercase tracking-[0.18em] text-navy">Trusted by Financial Institutions</p><div className="flex flex-wrap justify-center gap-x-8 gap-y-3 text-xs font-semibold text-muted-foreground"><span>Banks</span><span>NBFCs</span><span>HFCs</span><span>Small Finance Banks</span><span>Co-operative Banks</span></div></div></section>
  <section className="py-24"><div className="section-shell grid items-center gap-14 lg:grid-cols-2"><div><SectionHeading eyebrow="About bankNilami" title="A Managed Ecosystem for Bank Property Realisation"/><p className="mt-7 leading-8 text-muted-foreground">bankNilami.com manages secured property auctions on behalf of Banks, NBFCs, HFCs and Co-operative Banks — handling the process from valuation-readiness through to sale confirmation and final account settlement.</p><p className="mt-4 leading-8 text-muted-foreground">We act as the auction execution arm for our partner institutions, ensuring every sale is transparent, well-marketed and compliant with SARFAESI and other applicable regulatory norms.</p><Button asChild variant="outline" className="mt-8"><Link to="/about">About our approach <ArrowRight/></Link></Button></div><div className="subtle-grid relative min-h-[430px] overflow-hidden rounded-lg border border-border bg-surface p-8"><div className="absolute right-8 top-8 rounded-sm bg-gold px-3 py-2 text-[10px] font-bold uppercase tracking-[0.14em] text-navy">Institutional Auction Execution Partner</div><div className="absolute bottom-8 left-8 right-8 grid gap-3"><div className="rounded-md bg-navy p-6 text-navy-foreground"><div className="flex items-center justify-between"><Landmark className="text-gold"/><span className="text-xs text-navy-foreground/50">01 / 03</span></div><p className="display-serif mt-9 text-2xl">Readiness, reach and regulatory discipline.</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-md border border-border bg-background p-5"><ShieldCheck className="text-gold-strong"/><p className="mt-5 text-sm font-bold text-navy">Transparent execution</p></div><div className="rounded-md border border-border bg-background p-5"><FileBarChart className="text-gold-strong"/><p className="mt-5 text-sm font-bold text-navy">Centralised MIS</p></div></div></div></div></div></section>
  <section className="bg-surface py-24"><div className="section-shell"><SectionHeading eyebrow="Integrated capability" title="What We Deliver" intro="Specialist support across every stage of the secured-property auction lifecycle."/><div className="mt-12"><ServiceGrid/></div></div></section>
  <section className="py-24"><div className="section-shell"><SectionHeading eyebrow="End-to-end execution" title="The Auction & Realisation Journey" intro="We manage the property auction journey end to end — from valuation and readiness through to final proceeds settlement — with complete visibility at every stage."/><JourneyTimeline/></div></section>
  <section className="border-y border-border bg-surface py-24"><div className="section-shell"><SectionHeading eyebrow="Structured value creation" title="Turning Secured Assets Into Realisation"/><ProcessValueFlow/></div></section>
  <section className="py-24"><div className="section-shell"><SectionHeading eyebrow="Institutional relationships" title="Our Partner Institutions" intro="We currently manage bank property auction work for the following institutional partners:"/><div className="mt-12"><PartnerGrid/></div></div></section>
  <section className="bg-navy py-24 text-navy-foreground"><div className="section-shell"><SectionHeading light eyebrow="Demonstrated execution" title="Our Track Record" intro="Experience, institutional relationships and execution discipline across the secured-property auction lifecycle."/><div className="mt-12"><Stats dark/></div></div></section>
  <section className="py-24"><div className="section-shell grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Institutional advantage" title="Why Partner With Us" intro="One accountable team, disciplined process and complete visibility from first review to final settlement."/><ReasonsGrid/></div></section>
  <section className="subtle-grid bg-navy py-24 text-center text-navy-foreground"><div className="section-shell"><p className="display-serif text-4xl md:text-6xl">We don't just conduct auctions.</p><p className="display-serif mx-auto mt-5 max-w-5xl text-4xl font-semibold text-gold md:text-6xl">We protect value, drive competitive bidding, and deliver realisation.</p></div></section>
  <section className="bg-surface py-24"><div className="section-shell"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading eyebrow="Property discovery" title="Discover Bank Auction Properties" intro="Preview the future property discovery experience. All properties shown are clearly marked demonstration data."/><Button asChild variant="outline"><Link to="/auctions">View All Auctions <ArrowRight/></Link></Button></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{auctions.map(a=><AuctionCard key={a.id} auction={a}/>)}</div></div></section>
  <section className="bg-navy py-24"><div className="section-shell grid items-center gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading light eyebrow="Technology-enabled execution" title="Complete Visibility Across the Auction Lifecycle" intro="A central view of active auctions, buyer engagement, bids, sale confirmations and realisation reporting."/><div><DashboardMock/><p className="mt-4 text-center text-xs uppercase tracking-[0.16em] text-navy-foreground/50">Centralised MIS & Realisation Reporting — Concept View</p></div></div></section>
  <section className="py-24"><div className="section-shell grid gap-14 lg:grid-cols-2"><SectionHeading eyebrow="Governed process" title="Built Around Transparency & Compliance" intro="Clear workflows and auditable records support institutional teams across each stage of execution."/><div><ComplianceList/><p className="mt-8 rounded-md border border-border bg-surface p-5 text-xs leading-6 text-muted-foreground">Processes and regulatory requirements may vary based on the applicable institution, asset and jurisdiction. Specific auction terms are governed by the relevant statutory notices and institutional documentation.</p></div></div></section>
  <CTASection/>
  <section className="bg-surface py-24"><div className="section-shell grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><SectionHeading eyebrow="Institutional enquiries" title="Partner With Us" intro="Tell us about your institution or auction requirement. Our team can discuss the appropriate next step."/><div className="mt-8 space-y-3 text-sm"><a href="tel:+918094000405" className="block font-bold text-navy">8094 000 405</a><a href="mailto:info.banknilami@gmail.com" className="block text-primary">info.banknilami@gmail.com</a><p className="pt-3 leading-7 text-muted-foreground">{offices.join("  |  ")}</p></div></div><ContactForm/></div></section>
  </>}