import { Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, Building2, CalendarDays, Check, ChevronRight, CircleCheck, ClipboardCheck, FileCheck2, Gavel, Landmark, MapPin, Megaphone, Search, ShieldCheck, TrendingUp, UserCheck, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { auctions, journey, partners, reasons, services, stats, type Auction } from "@/lib/site-data";
import { SectionHeading } from "./site";

const iconMap = { FileCheck2, Megaphone, Gavel, UserCheck, TrendingUp, Landmark };

export function Stats({ dark=false }: { dark?: boolean }) { return <div className={`grid grid-cols-2 border ${dark ? "border-navy-foreground/15" : "border-border"} lg:grid-cols-4`}>{stats.map((s,i)=><div key={s.label} className={`p-5 md:p-7 ${i%2!==0 ? "border-l" : ""} ${i>1 ? "border-t lg:border-t-0" : ""} lg:border-l first:lg:border-l-0 ${dark ? "border-navy-foreground/15" : "border-border"}`}><strong className={`display-serif block text-3xl md:text-4xl ${dark ? "text-gold" : "text-navy"}`}>{s.value}</strong><span className={`mt-1 block text-xs ${dark ? "text-navy-foreground/60" : "text-muted-foreground"}`}>{s.label}</span></div>)}</div>; }

export function ServiceGrid({ compact=false }: { compact?: boolean }) { return <div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{services.map((s)=>{const Icon=iconMap[s.icon as keyof typeof iconMap]; return <article key={s.title} className={`group bg-background ${compact ? "p-7" : "p-8 md:p-10"} transition-colors hover:bg-surface`}><Icon className="mb-7 size-7 text-gold-strong transition-transform group-hover:-translate-y-1"/><h3 className="display-serif text-2xl font-semibold text-navy">{s.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{s.text}</p></article>})}</div>; }

export function JourneyTimeline() { return <div className="relative mt-14 grid gap-8 lg:grid-cols-3 xl:grid-cols-6"><div className="absolute left-0 right-0 top-8 hidden h-px bg-border xl:block"/>{journey.map((step,i)=><article key={step.title} className="relative pl-16 xl:pl-0"><div className="absolute left-0 top-0 flex size-12 items-center justify-center rounded-full border border-gold bg-background font-mono text-xs font-bold text-gold-strong xl:relative xl:z-10 xl:mb-8">{String(i+1).padStart(2,"0")}</div><div className="absolute bottom-0 left-6 top-12 w-px bg-border xl:hidden"/><h3 className="text-base font-bold leading-6 text-navy">{step.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{step.text}</p></article>)}</div>; }

export function PartnerGrid() { return <div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{partners.map(p=><article key={p.name} className="group flex min-h-52 flex-col justify-between bg-background p-7 hover:bg-surface"><div className="display-serif flex size-14 items-center justify-center rounded-full border border-border bg-surface text-xl font-semibold text-navy">{p.mark}</div><div><h3 className="font-bold text-navy">{p.name}</h3><p className="mt-1 text-xs uppercase tracking-[0.12em] text-muted-foreground">{p.type}</p></div></article>)}</div>; }

export function ReasonsGrid() { return <div className="grid gap-x-10 gap-y-3 md:grid-cols-2">{reasons.map(([title,text],i)=><article key={title} className="flex gap-5 border-b border-border py-7"><span className="display-serif text-xl text-gold-strong">0{i+1}</span><div><h3 className="font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></article>)}</div>; }

export function AuctionCard({ auction }: { auction: Auction }) { return <article className="group overflow-hidden rounded-lg border border-border bg-background transition-all hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[3/2] overflow-hidden"><img src={auction.image} alt={`Demo ${auction.type.toLowerCase()} property in ${auction.city}`} loading="lazy" width={1200} height={800} className="size-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"/><span className="absolute left-4 top-4 rounded-sm bg-gold px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[0.15em] text-navy">Demo / Sample</span></div><div className="p-6"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[0.15em] text-gold-strong">{auction.type}</p><p className="flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="size-3.5"/>{auction.date}</p></div><h3 className="display-serif mt-3 text-2xl font-semibold text-navy">{auction.title}</h3><p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="size-4"/>{auction.location}</p><div className="mt-6 flex items-end justify-between border-t border-border pt-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Reserve price</p><p className="mt-1 text-lg font-bold text-navy">{auction.reserve}</p></div><Button asChild variant="outline" size="sm"><Link to="/auction/$id" params={{id:auction.id}}>View Details <ArrowRight/></Link></Button></div></div></article>; }

export function AuctionFilters() { const [type,setType]=useState("All"); const [city,setCity]=useState("All"); const filtered=useMemo(()=>auctions.filter(a=>(type==="All"||a.type===type)&&(city==="All"||a.city===city)),[type,city]); return <><div className="mb-8 grid gap-4 rounded-lg border border-border bg-surface p-5 md:grid-cols-[1fr_1fr_auto]"><label className="text-xs font-bold uppercase tracking-[0.1em] text-muted-foreground">Property type<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 text-sm font-medium normal-case tracking-normal"><option>All</option><option>Commercial</option><option>Residential</option><option>Industrial</option></select></label><label className="text-xs font-bold uppercase tracking-[0.1em] text-muted-foreground">City<select value={city} onChange={e=>setCity(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 text-sm font-medium normal-case tracking-normal"><option>All</option><option>Ahmedabad</option><option>Jaipur</option><option>Hyderabad</option></select></label><Button variant="outline" className="self-end" onClick={()=>{setType("All");setCity("All")}}>Reset filters</Button></div>{filtered.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map(a=><AuctionCard auction={a} key={a.id}/>)}</div> : <div className="rounded-lg border border-dashed border-border py-20 text-center"><Search className="mx-auto mb-4 text-muted-foreground"/><h3 className="font-bold text-navy">No sample properties match</h3><p className="mt-2 text-sm text-muted-foreground">Reset the filters to view all demonstration listings.</p></div>}</>; }

export function ContactForm() { const [status,setStatus]=useState<"idle"|"submitting"|"success">("idle"); const [errors,setErrors]=useState<Record<string,string>>({}); function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); const data=new FormData(e.currentTarget); const next:Record<string,string>={}; ["name","company","phone","email","requirement"].forEach(k=>{if(!String(data.get(k)||"").trim()) next[k]="Required"}); const email=String(data.get("email")||""); if(email&&!/^\S+@\S+\.\S+$/.test(email)) next.email="Enter a valid email"; setErrors(next); if(Object.keys(next).length)return; setStatus("submitting"); window.setTimeout(()=>setStatus("success"),700)} if(status==="success") return <div role="status" className="rounded-lg border border-positive/30 bg-positive/5 p-10 text-center"><CircleCheck className="mx-auto size-10 text-positive"/><h3 className="display-serif mt-4 text-3xl font-semibold text-navy">Enquiry prepared</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Email delivery is not connected yet. Please call 8094 000 405 or email info.banknilami@gmail.com to submit your enquiry.</p><Button className="mt-6" variant="outline" onClick={()=>setStatus("idle")}>Send another enquiry</Button></div>; return <form onSubmit={submit} noValidate className="grid gap-5 sm:grid-cols-2">{[["name","Full Name"],["company","Company / Institution"],["designation","Designation"],["phone","Phone Number"],["email","Email Address"],["city","City"]].map(([name,label])=><label key={name} className="text-sm font-semibold text-navy">{label}{["name","company","phone","email"].includes(name)&&" *"}<Input name={name} type={name==="email"?"email":name==="phone"?"tel":"text"} aria-invalid={Boolean(errors[name])} className="mt-2 h-11 bg-background"/>{errors[name]&&<span className="mt-1 block text-xs text-destructive">{errors[name]}</span>}</label>)}<label className="text-sm font-semibold text-navy sm:col-span-2">Property / Auction Requirement *<Input name="requirement" className="mt-2 h-11 bg-background" aria-invalid={Boolean(errors.requirement)}/>{errors.requirement&&<span className="mt-1 block text-xs text-destructive">{errors.requirement}</span>}</label><label className="text-sm font-semibold text-navy sm:col-span-2">Message<Textarea name="message" className="mt-2 min-h-28 bg-background"/></label><div className="sm:col-span-2"><Button type="submit" size="lg" variant="institutional" disabled={status==="submitting"}>{status==="submitting"?"Preparing…":"Submit Enquiry"}<ArrowRight/></Button><p className="mt-3 text-xs text-muted-foreground">This form is currently a demonstration and does not transmit data.</p></div></form>; }

export function DashboardMock() { const metrics=[["Active Auctions","128"],["Upcoming Auctions","46"],["Buyer Enquiries","1,284"],["Bids Received","392"],["Sale Confirmations","31"],["Realisation Value","₹284 Cr"]]; return <div className="overflow-hidden rounded-lg border border-navy-foreground/15 bg-navy-soft shadow-2xl"><div className="flex items-center justify-between border-b border-navy-foreground/10 p-4"><span className="text-xs font-bold uppercase tracking-[0.15em] text-navy-foreground/65">Institutional overview</span><span className="flex items-center gap-2 text-xs text-positive"><span className="size-2 rounded-full bg-positive animate-pulse-soft"/>Live visibility</span></div><div className="grid grid-cols-2 gap-px bg-navy-foreground/10 md:grid-cols-3">{metrics.map(([label,value])=><div key={label} className="bg-navy-soft p-5"><p className="text-[10px] uppercase tracking-[0.12em] text-navy-foreground/45">{label}</p><p className="mt-2 text-xl font-bold text-navy-foreground">{value}</p></div>)}</div><div className="grid gap-5 p-5 md:grid-cols-[1.5fr_1fr]"><div className="h-40 rounded-md border border-navy-foreground/10 p-4"><p className="text-xs text-navy-foreground/60">Realisation trend</p><div className="mt-5 flex h-20 items-end gap-2">{[35,58,43,72,64,87,78,95].map((h,i)=><span key={i} className="flex-1 rounded-t-sm bg-gold/70" style={{height:`${h}%`}}/>)}</div></div><div className="rounded-md border border-navy-foreground/10 p-4"><p className="text-xs text-navy-foreground/60">MIS reports</p>{["Portfolio summary","Auction status","Proceeds report"].map(x=><p key={x} className="mt-3 flex items-center justify-between text-xs text-navy-foreground/80"><span>{x}</span><ChevronRight className="size-3"/></p>)}</div></div></div>; }

export function ComplianceList() { return <div className="grid gap-3 sm:grid-cols-2">{["SARFAESI-aligned auction processes","Documentation workflows","Transparent bidding","Buyer verification","Audit-friendly records","MIS and reporting","Sale confirmation workflow","Proceeds reconciliation"].map(x=><div key={x} className="flex items-center gap-3 border-b border-border py-4 text-sm font-semibold text-navy"><Check className="size-4 text-gold-strong"/>{x}</div>)}</div>; }

export function CTASection() { return <section className="bg-gold"><div className="section-shell flex flex-col items-start justify-between gap-8 py-14 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-navy/60">Your next property auction</p><h2 className="display-serif mt-2 text-4xl font-semibold text-navy md:text-5xl">Let's Resolve. Let's Realise.</h2><p className="mt-3 text-sm text-navy/70">Partner with bankNilami.com for your next property auction.</p></div><div className="flex flex-wrap gap-3"><Button asChild size="lg" variant="institutional"><Link to="/contact">Partner With Us <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><a href="tel:+918094000405">8094 000 405</a></Button></div></div></section>; }

export function ProcessValueFlow() { const items=["Secured Asset","Auction Readiness","Market Visibility","Verified Buyers","Competitive Bidding","Sale Confirmation","Realisation & Settlement"]; return <div className="mt-12 grid items-center gap-2 sm:grid-cols-2 lg:grid-cols-7">{items.map((x,i)=><div key={x} className="relative flex min-h-24 items-center justify-center rounded-md border border-border bg-background p-4 text-center text-sm font-bold text-navy shadow-sm">{x}{i<items.length-1&&<ArrowRight className="absolute -right-4 z-10 hidden size-5 rounded-full bg-surface text-gold-strong lg:block"/>}</div>)}</div>; }